### ISSUE TITLE
Volatile messages

### ISSUE THREAD

**Issue by insomnia-pt** [agsh/rtsp-ffmpeg#14]
I suggest a small change, case to a certain client is not ready to receive messages (network slowness or other issues)..

Use "volatile" messages:
`socket.volatile.emit('data', data.toString('base64'));`

If the client doesn't receive all "frames", the application will not be affected.

**Comment by Seikon** [comment]
Hi @insomnia-pt Thank you for the sugestion, but the scope of this library is in TCP based context, so i think is not necesary to deal with volatile messages. Also RTPS provides sessions that controll the whole transmisson of packets. I have tested the examples with ip cams on slow network and it seems all frames are given to all clients perfectly, but if you noticed some anomaly releated with volatile messages, we change to volatile instead emit directly.
