### ISSUE TITLE
How do I switch RTSP streams?

### ISSUE THREAD

**Issue by Caraws** [agsh/rtsp-ffmpeg#16]
I want to switch the camera screen with the button on the client side. So i did this.

![code](http://orf90agxq.bkt.clouddn.com/GitHubQQ%E6%88%AA%E5%9B%BE20170726120142.png)

![consle](http://orf90agxq.bkt.clouddn.com/GitHubQQ%E6%88%AA%E5%9B%BE20170726120234.png)

but the client didn't change. am i did wrong? please tell me the right way.

**Comment by agsh** [comment]
Try `restart()` method after changing `input` property.

**Comment by Caraws** [comment]
cool! it's work, thx a lot!!
