### ISSUE TITLE
ffmpeg ENONET

### ISSUE THREAD

**Issue by alxgeoaln** [agsh/rtsp-ffmpeg#17]
const url = 'rtsp://user:pass@123.133.166.636:554';
const stream = new rtsp.FFMpeg({input: url});

io.on('connection', function(socket) {
    console.log('user');
    var pipeStream = function(data) {
        socket.emit('data', data.toString('base64'));
    };
    stream.on('data', pipeStream);
    socket.on('disconnect', function() {
        stream.removeListener('data', pipeStream);
    });
});

and client 

<script src="/socket.io/socket.io.js"></script>
<script>
    var img = document.getElementById('img'),
        socket = io();
    socket.on('data', function(data) {
        img.src = 'data:image/jpeg;base64,' + data;
    });
</script>

I get this error 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

plese help! Thanks

**Comment by agsh** [comment]
You haven't got ffmpeg installed on your machine.
