### ISSUE TITLE
Restart method

### ISSUE THREAD

**Issue by pirquessa** [agsh/rtsp-ffmpeg#2]
I notice that the restart method was not declared as stop/start on the prototype... Is that normal ?

See line 111:

FFMpeg.restart = function() 

When replaced by

FFMpeg.prototype.restart = function()

I can restart the streaming if needed.

**Comment by agsh** [comment]
Yeah, you are absolutely right! This is a misspell. Thank you.

**Comment by pirquessa** [comment]
\o/ First usefull participation on a repo \o/

Thanks for your lib !

Do you think there is a way to get an event when ffmpeg crash & reboot ? (It seems to do it a lot when the camera is down)

Other question: how to know that the camera is down ?

Thanks again :)

**Comment by agsh** [comment]
When something goes wrong with ffmpeg, you can uncomment these two lines: https://github.com/agsh/rtsp-ffmpeg/blob/master/lib/rtsp-ffmpeg.js#L95 and write everything you want.
And when the camera is down, ffmpeg doesn't produce any data, so you can handle a timeout to check activity on `data` event. Better solution is to ping camera and find out what's happening.

**Comment by pirquessa** [comment]
"error" callback can be removed / stay commented, It does not seems to be trigger. Even if the ffmpeg process die or restart.
The "close" callback seems to be triggered when the camera stream come back, not when it disappear :(
