### ISSUE TITLE
RTSP H264 stream no image output no error, how to turn error log on

### ISSUE THREAD

**Issue by deqoder** [agsh/rtsp-ffmpeg#20]
My stream source is in RTSP protocol and H264 encode from camera, tested with VLC is OK, but use `example/server.js` and select cam3(my own cam) there is no image output, no error output, if I select cam0, its OK.
I add console.log before `wsocket.emit('data', data);` in `example/server.js`, and I can see `console.log` is not called when use cam3(my own cam).

I see this in `../lib/rtsp-ffmpeg.js`
```

FFMpeg.prototype._args = function() {
        return this.arguments.concat([
                '-loglevel', 'quiet'
```

So, how to turn loglevel to highest

**Comment by deqoder** [comment]
I solved myself.

**Comment by evang9410** [comment]
@deqoder can you please elaborate on how you solved this issue? I am experiencing the same thing
