### ISSUE TITLE
[Windows] Unrecognized option updatefirst

### ISSUE THREAD

**Issue by Zombitch** [agsh/rtsp-ffmpeg#24]
Hello,

On windows plateform, running the provided example give the following error : 

_Unrecognized option updatefirst_

Then if I comment the line **_, '-updatefirst', '1'_** on rtsp-ffmpeg.js I get another error : 

_Error: Trailing options were found on the commandline._

Any chance to get a fix for this please ?

Regards,
Zombitch

**Comment by agsh** [comment]
Hi!
Please try to put `'-'` argument last in the array.

**Comment by Zombitch** [comment]
Hey agsh !

According to the following [ffmpeg patch 5737](https://patchwork.ffmpeg.org/patch/5737/), **updatefirst** option has been removed and "replaced" by **update**. 
So it doesn't seem to be a windows problem, I was misled because it was working on my rpi (debian) with an "old" ffmpeg version but not on windows with the latest ffmpeg version.

In other words, replacing **'-updatefirst', '1'** by **'-updatefirst', '1'** works.

As the comment on the 5737 patch point out, **update** option should be used instead of **udpatefirst** , cause updatefirst is a redundant  option to **update**.
I'll do some tests on both of my computer and pull a request if tests are successful.

Regards,
Zombitch
