### ISSUE TITLE
Enhancement: Allow to use custom ffmpeg params

### ISSUE THREAD

**Issue by pirquessa** [agsh/rtsp-ffmpeg#3]
I had to customize the lib to be able to use parameter like "-vf crop=ih:ih:(iw-ih)/2:0, transpose=2" in FFMpeg.prototype._args method. 

It could be good to expose a way for the user to use custom parameters... A callback ? A generic array that will be concat to existing params ?

Could you do it for me ? :-D

**Comment by agsh** [comment]
Just add an `arguments` option in the constructor. You can pass parameters in [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) style like this:

``` js
{
  arguments: ['-vf', 'crop=ih:ih:(iw-ih)/2:0']
}
```

**Comment by pirquessa** [comment]
Nice ! I'll try it tonight :)

Thanks

**Comment by pirquessa** [comment]
Fail :(

There is a strange '-' as last argument in the FFMpeg.prototype._args method. It looks like we have to keep it at the end. You know why ?

The fact is that the fix does not works... Using this.arguments as the fist argument of the concat method make it works.

**Comment by agsh** [comment]
Oh, crap. Forgot about dash at the end which forces ffmpeg to use stdin. f65da575e8cb0510c3a325b0a0d048cd37703a8c

**Comment by pirquessa** [comment]
Seems better now. Thx :)

Do you update the npm repo each time ?

**Comment by agsh** [comment]
For this small library - yes.
