### ISSUE TITLE
Resolution setting does not work

### ISSUE THREAD

**Issue by Venryx** [agsh/rtsp-ffmpeg#33]
The resolution setting does not work currently: the setting is completed ignored.

The reason is that the code places the scaling flag (`-s XXX`) _after_ the pipe flag (`-`), which makes it ignored:
```
return this.arguments.concat(
  [ <other flags> ]
  , [ <other flags> , '-']
  , this.resolution ? ['-s', this.resolution] : []
);
```

To fix, I simply moved the resolution flag before the pipe-flag:
```
return this.arguments.concat(
  [ <other flags> ]
  , this.resolution ? ['-s', this.resolution] : []
  , [ <other flags> , '-']
);
```

**Comment by agsh** [comment]
Ooops, missed that! Fixed it, please check

**Comment by Venryx** [comment]
Yep, that fixed it. Thanks!
