### ISSUE TITLE
Add way to include additional ffmpeg flags

### ISSUE THREAD

**Issue by Venryx** [agsh/rtsp-ffmpeg#34]
The library is a nice wrapper around receiving frames from ffmpeg, but it's a hassle when you want to include an extra flag for ffmpeg, but the library has no way to do so.

Perhaps an `options.additionalFlags` property (which is appended to the arguments list -- well, just before the pipe-flag, as mentioned in my other issue) would be sufficient.

**Comment by agsh** [comment]
You can use `options.arguments` for this case

**Comment by Venryx** [comment]
Oops. I don't know how I missed that. XD

Thanks.
