### ISSUE TITLE
Examples...

### ISSUE THREAD

**Issue by funky81** [agsh/rtsp-ffmpeg#4]
Hi, i'm trying your libraries here. but i confused how to run it.
what i do is run node examples\server.js then run browser points to http://localhost:6147
but it doesnt do anything.
try to debug with firebug, and i've got many request aborted.

Thanks

**Comment by agsh** [comment]
I confirm this. I'll make working example in the next few days.

**Comment by funky81** [comment]
Thanks. Looking forward to see the solution.

**Comment by agsh** [comment]
This was socket.io bug, it omits port when no server is specified. Fixed in bbe9dc9e15d45af709edfa90a9ba4b32e0e713dd
