### ISSUE TITLE
can i run this without socketIO ?

### ISSUE THREAD

**Issue by riskiadi** [agsh/rtsp-ffmpeg#40]
can i run this library without socketIO ?

**Comment by agsh** [comment]
@riskiadi Hi! Yes sure, the library only emits video fragments. Socket.io uses only in the example

**Comment by riskiadi** [comment]
> @riskiadi Hi! Yes sure, the library only emits video fragments. Socket.io uses only in the example

ok thanks, I just star this repo, :)
